#!/bin/bash
# Runs data through train.py multiple times given a set of parameters 

cat "$1" | while IFS= read -r line
do 
    mkdir args.outf
    mkdir args.outf/sample
    python train.py $line
done
